baseURL = "//demaree.me/"
languageCode = "en-us"
title = "David Demaree"
description = "Writing, photos, and nonsense from a NYC-based tech person"
theme = "demaree-2022"

# Disable Hugo's built-in Alias feature, to utilize Netlify Redirects instead:
disableAliases = true

[taxonomies]
series = "series"
tag = "tags"

[social]
twitter = "ddemaree"
instagram = "ddemaree"
github = "ddemaree"
linkedin = "ddemaree"

[params]
cloudinaryBase = "res.cloudinary.com/demaree/image"

[permalinks]
posts = "/p/:slug"

[markup]
[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false
  style = "monokai"
  tabWidth = 2

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true
  title = true


[[menu.social]]
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class='fab fa-twitter'></i>"
  url = "https://twitter.com/ddemaree"
  weight = -100

[[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class='fab fa-instagram'></i>"
  url = "https://instagram.com/ddemaree"

[[menu.social]]
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "<i class='fab fa-linkedin'></i>"
  url = "https://linkedin.com/in/ddemaree"

[outputFormats]
[outputFormats.RSS]
  baseName = "feed"
  isPlainText = true
  mediatype = "application/rss+xml"
  permalinkable = true

[outputFormats.SVG]
  baseName = "icon"
  isPlainText = true
  mediatype = "image/svg+xml"
  notAlternative = true
  permalinkable = true

[outputs]
  home = ["HTML", "RSS", "SVG"]