[Settings]
  ID = "demaree-next"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "16"

[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  status = 301

[[redirects]]
  from = "/posts"
  to = "/articles"
  status = 301

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8080