[Settings]
  ID = "demaree-next"

[build]
  command = "pnpm build"
  publish = "dist"

# [[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  # package = "@netlify/plugin-lighthouse"

[context.production]
  NODE_ENV = "production"
  NODE_VERSION = "18"

[[redirects]]
  from = "/feed"
  to = "/feeds/posts.xml"
  status = 301

[functions]
  external_node_modules = ["astro", "shiki"]

[dev]
  framework = "astro"