[Settings]
  ID = "demaree-next"

[build]
  command = "astro build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "16"

[[redirects]]
  from = "/feed"
  to = "/feeds/posts.xml"
  status = 301