[Settings]
  ID = "demaree-next"

[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "16"

[[redirects]]
  from = "/feed.xml"
  to = "https://demaree.blog/feed/atom"
  status = 301

[[redirects]]
  from = "/posts"
  to = "https://demaree.blog/"
  status = 301

[[redirects]]
  from = "https://demaree.me/*"
  to = "https://demaree.space/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://demaree.me/"
  to = "https://demaree.space/"
  status = 301
  force = true

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8080